# Generated by Django 3.2.4 on 2022-01-15 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='com_name',
        ),
    ]
