# Generated by Django 3.2.4 on 2022-01-15 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_person_com_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='com_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Company/Business Name'),
        ),
    ]
