# Generated by Django 3.2.4 on 2022-01-15 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_person_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='dob',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Start of Business'),
        ),
    ]
