# Generated by Django 3.2.4 on 2022-03-07 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_person_holding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='holding',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
