# Generated by Django 3.2.4 on 2022-04-08 09:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_person_holding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outlet',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outlet_manager', to=settings.AUTH_USER_MODEL, verbose_name='QwikVendor'),
        ),
    ]
