# Generated by Django 3.2.4 on 2022-03-14 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_person_holding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='holding',
            field=models.CharField(blank=True, max_length=110, null=True, verbose_name='Owing'),
        ),
    ]
