# Generated by Django 3.2.4 on 2022-01-15 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_item_status', models.CharField(default='New', max_length=16, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_status', models.CharField(choices=[('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], max_length=30, null=True, verbose_name='Select Present Order Status')),
                ('employee', models.CharField(blank=True, max_length=20, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Order Status',
                'verbose_name_plural': 'Order Statuses',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='PayDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_del_Id', models.CharField(max_length=10, null=True)),
                ('payment_choice', models.CharField(choices=[('Bank Transfer', 'Bank Transfer'), ('PoS', 'PoS'), ('Cash', 'Cash')], max_length=13, null=True, verbose_name='Payment Choice')),
                ('payment_ref', models.CharField(blank=True, max_length=40, null=True, verbose_name='Payment Reference (Bank Transfer)')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pay on Delivery',
                'verbose_name_plural': 'Pay on Deliveries',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='PayLater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_lat_Id', models.CharField(max_length=10, null=True)),
                ('payment_date_later', models.DateField(blank=True, null=True, verbose_name='Committed Payment Date')),
                ('payment_choice', models.CharField(choices=[('Bank Transfer', 'Bank Transfer'), ('PoS', 'PoS'), ('Cash', 'Cash')], max_length=13, null=True, verbose_name='Payment Choice')),
                ('payment_ref', models.CharField(blank=True, max_length=40, null=True, verbose_name='Payment Reference (Bank Transfer)')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='PaySmall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_sma_Id', models.CharField(max_length=10, null=True)),
                ('payment1', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='1st Payment')),
                ('payment1_date', models.DateField(blank=True, null=True, verbose_name='1st Payment Date')),
                ('payment2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='2nd Payment')),
                ('payment2_date', models.DateField(blank=True, null=True, verbose_name='2nd Payment Date')),
                ('payment3', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='3rd Payment')),
                ('payment3_date', models.DateField(blank=True, null=True, verbose_name='3rd Payment Date')),
                ('payment_choice', models.CharField(choices=[('Bank Transfer', 'Bank Transfer'), ('PoS', 'PoS'), ('Cash', 'Cash')], max_length=13, null=True, verbose_name='Payment Choice')),
                ('payment_ref', models.CharField(blank=True, max_length=40, null=True, verbose_name='Payment Reference (Bank Transfer)')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='UserOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_Id', models.CharField(max_length=10, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Delivery Address')),
                ('schedule_delivery', models.DateField(blank=True, null=True, verbose_name='Schedule Delivery')),
                ('payment_type', models.CharField(blank=True, max_length=15, null=True, verbose_name='Payment Type')),
                ('payment_date_later', models.DateField(blank=True, null=True, verbose_name='Committed Payment Date')),
                ('payment1', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='1st Payment')),
                ('payment1_date', models.DateField(blank=True, null=True, verbose_name='1st Payment Date')),
                ('payment2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='2nd Payment')),
                ('payment2_date', models.DateField(blank=True, null=True, verbose_name='2nd Payment Date')),
                ('payment3', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='3rd Payment')),
                ('payment3_date', models.DateField(blank=True, null=True, verbose_name='3rd Payment Date')),
                ('payment_choice', models.CharField(blank=True, max_length=13, null=True, verbose_name='Payment Choice')),
                ('payment_status', models.CharField(choices=[('Unconfirmed', 'Unconfirmed'), ('Confirmed', 'Confirmed')], default='Unconfirmed', max_length=12, null=True, verbose_name='Payment Status')),
                ('point', models.PositiveIntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
