# Generated by Django 3.2.4 on 2022-03-31 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20220331_2242'),
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderstatus',
            name='cylinder',
            field=models.ManyToManyField(related_name='order_status_cylinders', to='products.Product'),
        ),
        migrations.AddField(
            model_name='orderstatus',
            name='static_total_cost2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AddField(
            model_name='orderstatus',
            name='who7_2',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='userorder',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AddField(
            model_name='userorder',
            name='user_order_status',
            field=models.CharField(default='Undelivered', max_length=11, null=True),
        ),
    ]
