# Generated by Django 3.2.4 on 2022-03-01 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderstatus',
            name='who7_2',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
