# Generated by Django 3.2.4 on 2022-04-13 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20220331_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userorder',
            name='payment_status',
            field=models.CharField(choices=[('Confirmed', 'Confirmed')], default='Unconfirmed', max_length=12, null=True, verbose_name='Payment Status'),
        ),
    ]
