# Generated by Django 3.2.4 on 2022-03-11 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderstatus_who7_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='userorder',
            name='user_order_status',
            field=models.CharField(default='Undelivered', max_length=11, null=True),
        ),
    ]
