# Generated by Django 3.2.4 on 2022-03-14 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0033_alter_owing_cylinder'),
        ('orders', '0004_userorder_user_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderstatus',
            name='cylinder',
            field=models.ManyToManyField(related_name='order_status_cylinders', to='products.Product'),
        ),
    ]
