# Generated by Django 3.2.4 on 2022-04-13 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_userorder_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userorder',
            name='payment_status',
            field=models.CharField(choices=[('Unconfirmed', 'Unconfirmed'), ('Confirmed', 'Confirmed')], default='Unconfirmed', max_length=12, null=True, verbose_name='Payment Status'),
        ),
    ]
