# Generated by Django 3.2.4 on 2022-03-15 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_orderstatus_cylinder'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderstatus',
            name='static_total_cost2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
    ]
