# Generated by Django 3.2.4 on 2022-03-18 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_orderstatus_static_total_cost2'),
    ]

    operations = [
        migrations.AddField(
            model_name='userorder',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=13, null=True),
        ),
    ]
