# Generated by Django 3.2.4 on 2022-03-18 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_userorder_total_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userorder',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
    ]
