# Generated by Django 3.2.4 on 2022-01-15 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AntiOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_Id', models.CharField(blank=True, max_length=10, null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('payment_type1', models.CharField(choices=[('Pay Now', 'Pay Now')], max_length=7, null=True, verbose_name='Payment Type')),
                ('payment_type2', models.CharField(choices=[('Paylater', 'Paylater')], max_length=8, null=True, verbose_name='')),
                ('payment_type3', models.CharField(choices=[('Pay Small Small', 'Pay Small Small')], max_length=15, null=True, verbose_name='')),
                ('payment_date_later', models.DateField(blank=True, null=True, verbose_name='Committed Payment Date')),
                ('payment_split', models.CharField(blank=True, max_length=40, null=True, verbose_name='Payment Split in Amount')),
                ('payment_date_small', models.DateField(blank=True, null=True, verbose_name='Committed Payment Date')),
                ('payment_choice', models.CharField(choices=[('Bank Transfer', 'Bank Transfer'), ('PoS', 'PoS'), ('Cash', 'Cash')], max_length=13, null=True, verbose_name='Payment Choice')),
                ('payment_ref', models.CharField(blank=True, max_length=40, null=True, verbose_name='Payment Reference (Bank Transfer)')),
                ('payment1', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='1st Payment')),
                ('payment1_date', models.DateField(blank=True, null=True, verbose_name='1st Payment Date')),
                ('payment2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='2nd Payment')),
                ('payment2_date', models.DateField(blank=True, null=True, verbose_name='2nd Payment Date')),
                ('payment3', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='3rd Payment')),
                ('payment3_date', models.DateField(blank=True, null=True, verbose_name='3rd Payment Date')),
                ('transaction', models.CharField(blank=True, choices=[('Open', 'Open'), ('Closed', 'Closed')], default='Open', max_length=12, null=True, verbose_name='Transaction Status')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
