# Generated by Django 3.2.4 on 2022-03-13 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anticipate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='antiorder',
            name='cylinder',
        ),
    ]
