# Generated by Django 3.2.4 on 2022-03-13 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_owing'),
        ('anticipate', '0002_remove_antiorder_cylinder'),
    ]

    operations = [
        migrations.AddField(
            model_name='antiorder',
            name='cylinder',
            field=models.ManyToManyField(related_name='anti_cylinders', to='products.Cylinder'),
        ),
    ]
