# Generated by Django 3.2.4 on 2022-01-15 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anticipate', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='antiorder',
            name='static_price',
            field=models.DecimalField(decimal_places=2, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='antiorder',
            name='static_total_cost',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
    ]
