# Generated by Django 3.2.4 on 2022-03-13 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anticipate', '0003_antiorder_cylinder'),
    ]

    operations = [
        migrations.AddField(
            model_name='antiorder',
            name='category',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
