# Generated by Django 3.2.4 on 2022-01-15 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anticipate', '0003_auto_20220115_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antiorder',
            name='static_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='antiorder',
            name='static_total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
    ]
