# Generated by Django 3.2.4 on 2022-03-13 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anticipate', '0004_antiorder_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='antiorder',
            name='outlet_static',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
