# Generated by Django 3.2.7 on 2022-01-16 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anticipate', '0004_auto_20220115_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antiorder',
            name='payment_type1',
            field=models.CharField(blank=True, choices=[('Pay Now', 'Pay Now')], max_length=7, null=True, verbose_name='Payment Type'),
        ),
        migrations.AlterField(
            model_name='antiorder',
            name='payment_type2',
            field=models.CharField(blank=True, choices=[('Paylater', 'Paylater')], max_length=8, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='antiorder',
            name='payment_type3',
            field=models.CharField(blank=True, choices=[('Pay Small Small', 'Pay Small Small')], max_length=15, null=True, verbose_name=''),
        ),
    ]
