# Generated by Django 3.2.4 on 2022-03-13 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anticipate', '0005_antiorder_outlet_static'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antiorder',
            name='category',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='antiorder',
            name='outlet_static',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
