# Generated by Django 3.2.4 on 2022-03-01 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anticipate', '0005_auto_20220116_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='antiorder',
            name='who6_2',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
