# Generated by Django 3.2.4 on 2022-03-31 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20220331_2242'),
        ('anticipate', '0005_auto_20220116_2149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='antiorder',
            name='payment_date_small',
        ),
        migrations.AddField(
            model_name='antiorder',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='antiorder',
            name='category',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='antiorder',
            name='cylinder',
            field=models.ManyToManyField(related_name='anti_cylinders', to='products.Product'),
        ),
        migrations.AddField(
            model_name='antiorder',
            name='outlet_static',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='antiorder',
            name='payment_total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='antiorder',
            name='static_price2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='antiorder',
            name='static_total_cost2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AddField(
            model_name='antiorder',
            name='who6_2',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='antiorder',
            name='payment1',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='1st Payment'),
        ),
        migrations.AlterField(
            model_name='antiorder',
            name='payment_ref',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Payment Reference'),
        ),
        migrations.AlterField(
            model_name='antiorder',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anti_products', to='products.product'),
        ),
        migrations.AlterField(
            model_name='antiorder',
            name='static_total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=13, null=True),
        ),
    ]
