# Generated by Django 3.2.4 on 2022-03-13 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anticipate', '0006_auto_20220313_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antiorder',
            name='static_price',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='antiorder',
            name='static_total_cost',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
