# Generated by Django 3.2.4 on 2022-03-13 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0032_auto_20220313_2158'),
        ('anticipate', '0007_auto_20220313_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antiorder',
            name='cylinder',
            field=models.ManyToManyField(related_name='anti_cylinders', to='products.Product'),
        ),
    ]
