# Generated by Django 3.2.4 on 2022-04-19 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anticipate', '0007_auto_20220417_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antiorder',
            name='order_Id',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
