# Generated by Django 3.2.4 on 2022-03-13 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anticipate', '0008_alter_antiorder_cylinder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='antiorder',
            name='cylinder',
        ),
    ]
