# Generated by Django 3.2.4 on 2022-04-19 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anticipate', '0009_alter_antiorder_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antiorder',
            name='order_Id',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
    ]
