# Generated by Django 3.2.4 on 2022-04-19 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anticipate', '0011_alter_antiorder_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='antiorder',
            name='stage',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
