# Generated by Django 3.2.4 on 2022-03-14 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0032_auto_20220313_2158'),
        ('anticipate', '0011_remove_antiorder_cylinder'),
    ]

    operations = [
        migrations.AddField(
            model_name='antiorder',
            name='cylinder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anti_cylinders', to='products.product'),
        ),
    ]
