# Generated by Django 3.2.4 on 2022-05-04 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anticipate', '0013_auto_20220419_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antiorder',
            name='static_price2',
            field=models.CharField(blank=True, max_length=110, null=True),
        ),
    ]
