# Generated by Django 3.2.4 on 2022-03-14 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anticipate', '0013_auto_20220314_1039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='antiorder',
            name='cylinder',
        ),
    ]
