# Generated by Django 3.2.4 on 2022-03-14 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0032_auto_20220313_2158'),
        ('anticipate', '0014_remove_antiorder_cylinder'),
    ]

    operations = [
        migrations.AddField(
            model_name='antiorder',
            name='cylinder',
            field=models.ManyToManyField(related_name='anti_cylinders', to='products.Product'),
        ),
    ]
