# Generated by Django 3.2.4 on 2022-06-05 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anticipate', '0014_alter_antiorder_static_price2'),
    ]

    operations = [
        migrations.AddField(
            model_name='antiorder',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
