# Generated by Django 3.2.4 on 2022-06-05 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anticipate', '0015_antiorder_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antiorder',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
