# Generated by Django 3.2.4 on 2022-03-14 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anticipate', '0015_antiorder_cylinder'),
    ]

    operations = [
        migrations.AddField(
            model_name='antiorder',
            name='static_price2',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='antiorder',
            name='static_total_cost2',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='antiorder',
            name='static_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='antiorder',
            name='static_total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
    ]
