# Generated by Django 3.2.4 on 2022-03-14 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anticipate', '0016_auto_20220314_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antiorder',
            name='static_price2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='antiorder',
            name='static_total_cost2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
    ]
