# Generated by Django 3.2.4 on 2022-06-05 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anticipate', '0016_alter_antiorder_payment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='antiorder',
            name='payment_date',
        ),
    ]
