# Generated by Django 3.2.4 on 2022-03-17 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anticipate', '0017_auto_20220314_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='antiorder',
            name='payment_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
