# Generated by Django 3.2.4 on 2022-03-18 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anticipate', '0020_antiorder_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antiorder',
            name='static_total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=13, null=True),
        ),
    ]
