# Generated by Django 3.2.4 on 2022-03-18 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anticipate', '0023_alter_antiorder_payment1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antiorder',
            name='payment1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='1st Payment'),
        ),
        migrations.AlterField(
            model_name='antiorder',
            name='static_total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=13, null=True),
        ),
    ]
