# Generated by Django 3.2.4 on 2022-03-18 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anticipate', '0024_auto_20220318_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antiorder',
            name='payment1',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='1st Payment'),
        ),
    ]
