# Generated by Django 3.2.4 on 2022-03-18 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anticipate', '0026_auto_20220318_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antiorder',
            name='payment2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='2nd Payment'),
        ),
        migrations.AlterField(
            model_name='antiorder',
            name='payment3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='3rd Payment'),
        ),
    ]
