# Generated by Django 3.2.4 on 2022-01-15 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(db_index=True, max_length=20, unique=True)),
                ('mass', models.CharField(db_index=True, max_length=6, unique=True)),
                ('slug', models.SlugField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=11, null=True)),
                ('tare', models.CharField(db_index=True, max_length=6, null=True, unique=True)),
                ('working', models.CharField(db_index=True, max_length=6, null=True)),
                ('test', models.CharField(db_index=True, max_length=6, null=True)),
                ('water', models.CharField(db_index=True, max_length=6, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories_img/%Y/%m/%d')),
                ('description', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ('type',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_Id', models.CharField(max_length=20, null=True, unique=True, verbose_name='Cylinder Id')),
                ('available', models.BooleanField(default=False, max_length=5)),
                ('vendor_product_status', models.CharField(choices=[('Dispatched Empty', 'Dispatched Empty'), ('Received Empty', 'Received Empty'), ('Dispatched Filled', 'Dispatched Filled'), ('Received Filled', 'Received Filled')], max_length=30, null=True, verbose_name='Remark')),
                ('vendor_product', models.CharField(blank=True, max_length=20, null=True)),
                ('partner_product_status', models.CharField(blank=True, choices=[('Returned Empty', 'Returned Empty'), ('Received Empty', 'Received Empty'), ('Delivered to Plant', 'Delivered to Plant'), ('Received Filled', 'Received Filled'), ('Delivered to QwikCustomer', 'Delivered to QwikCustomer')], max_length=30, null=True, verbose_name="QwikPartner's Remark")),
                ('partner_product', models.CharField(blank=True, max_length=20, null=True)),
                ('batch_Id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_category', to='products.category', verbose_name='Product')),
            ],
            options={
                'ordering': ('product_Id',),
            },
        ),
    ]
