# Generated by Django 3.2.4 on 2022-01-15 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='outlet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.outlet'),
        ),
        migrations.AlterIndexTogether(
            name='product',
            index_together={('id',)},
        ),
    ]
