# Generated by Django 3.2.7 on 2022-01-29 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='admin_product',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='admin_product_status',
            field=models.CharField(blank=True, choices=[('Returned Empty to QwikLet', 'Returned Empty to QwikLet'), ('Received Empty from QwikCustomer', 'Received Empty from QwikCustomer'), ('Delivered Filled to QwikLet', 'Delivered Filled to QwikLet'), ('Dispatched Filled to QwikCustomer', 'Dispatched Filled to QwikCustomer'), ('Delivered Filled to QwikCustomer', 'Delivered Filled to QwikCustomer'), ('Returned Filled to QwikLet', 'Returned Filled to QwikLet'), ('Dispatched to Plant', 'Dispatched to Plant'), ('Delivered to Plant', 'Delivered to Plant'), ('Returned Empty', 'Returned Empty'), ('Received Empty', 'Received Empty'), ('Received Filled', 'Received Filled')], max_length=35, null=True, verbose_name="QwikAdmin's Remark"),
        ),
        migrations.AddField(
            model_name='product',
            name='customer_product',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='customer_product_status',
            field=models.CharField(blank=True, choices=[('Returned Empty to QwikLet', 'Returned Empty to QwikLet'), ('Received Empty from QwikCustomer', 'Received Empty from QwikCustomer'), ('Delivered Filled to QwikLet', 'Delivered Filled to QwikLet'), ('Dispatched Filled to QwikCustomer', 'Dispatched Filled to QwikCustomer'), ('Delivered Filled to QwikCustomer', 'Delivered Filled to QwikCustomer'), ('Returned Filled to QwikLet', 'Returned Filled to QwikLet'), ('Dispatched to Plant', 'Dispatched to Plant'), ('Delivered to Plant', 'Delivered to Plant'), ('Returned Empty', 'Returned Empty'), ('Received Empty', 'Received Empty'), ('Received Filled', 'Received Filled')], max_length=35, null=True, verbose_name="QwikCustomer's Remark"),
        ),
        migrations.AlterField(
            model_name='product',
            name='partner_product_status',
            field=models.CharField(blank=True, choices=[('Returned Empty to QwikLet', 'Returned Empty to QwikLet'), ('Received Empty from QwikCustomer', 'Received Empty from QwikCustomer'), ('Delivered Filled to QwikLet', 'Delivered Filled to QwikLet'), ('Dispatched Filled to QwikCustomer', 'Dispatched Filled to QwikCustomer'), ('Delivered Filled to QwikCustomer', 'Delivered Filled to QwikCustomer'), ('Returned Filled to QwikLet', 'Returned Filled to QwikLet'), ('Dispatched to Plant', 'Dispatched to Plant'), ('Delivered to Plant', 'Delivered to Plant'), ('Returned Empty', 'Returned Empty'), ('Received Empty', 'Received Empty'), ('Received Filled', 'Received Filled')], max_length=35, null=True, verbose_name="QwikPartner's Remark"),
        ),
        migrations.AlterField(
            model_name='product',
            name='vendor_product_status',
            field=models.CharField(choices=[('Dispatched Empty to Plant', 'Dispatched Empty to Plant'), ('Returned Empty to QwikLet', 'Returned Empty to QwikLet'), ('Delivered Filled to QwikLet', 'Delivered Filled to QwikLet'), ('Released Filled to QwikPartner', 'Released Filled to QwikPartner'), ('Delivered to QwikCustomer', 'Delivered to QwikCustomer'), ('Returned Filled to QwikLet', 'Returned Filled to QwikLet'), ('Dispatched Empty', 'Dispatched Empty'), ('Received Empty', 'Received Empty'), ('Dispatched Filled', 'Dispatched Filled'), ('Received Filled', 'Received Filled')], max_length=30, null=True, verbose_name="QwikVendor's Remark"),
        ),
    ]
