# Generated by Django 3.2.4 on 2022-03-31 21:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='admin_product',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='admin_product_status',
            field=models.CharField(blank=True, choices=[('Received Empty from QwikCustomer', 'Received Empty from QwikCustomer'), ('Returned Empty to QwikLet', 'Returned Empty to QwikLet'), ('Dispatched to Plant', 'Dispatched to Plant'), ('Delivered Filled to QwikLet', 'Delivered Filled to QwikLet'), ('Dispatched Filled to QwikCustomer', 'Dispatched Filled to QwikCustomer'), ('Delivered to QwikCustomer', 'Delivered to QwikCustomer'), ('Returned Filled to QwikLet', 'Returned Filled to QwikLet')], max_length=35, null=True, verbose_name="QwikAdmin's Remark"),
        ),
        migrations.AddField(
            model_name='product',
            name='customer_product',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='customer_product_status',
            field=models.CharField(blank=True, choices=[('Returned Empty to QwikPartner', 'Returned Empty to QwikPartner'), ('Received Filled', 'Received Filled')], max_length=35, null=True, verbose_name="QwikCustomer's Remark"),
        ),
        migrations.AddField(
            model_name='product',
            name='partner_consent',
            field=models.BooleanField(default=False, max_length=5),
        ),
        migrations.AddField(
            model_name='product',
            name='vendor_consent',
            field=models.BooleanField(default=False, max_length=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='partner_product_status',
            field=models.CharField(blank=True, choices=[('Received Empty from QwikCustomer', 'Received Empty from QwikCustomer'), ('Returned Empty', 'Returned Empty'), ('Received Empty', 'Received Empty'), ('Received Filled', 'Received Filled')], max_length=35, null=True, verbose_name="QwikPartner's Remark"),
        ),
        migrations.AlterField(
            model_name='product',
            name='vendor_product_status',
            field=models.CharField(choices=[('Dispatched to Plant', 'Dispatched to Plant'), ('Released Filled to QwikPartner', 'Released Filled to QwikPartner'), ('Dispatched Empty', 'Dispatched Empty'), ('Received Empty', 'Received Empty'), ('Dispatched Filled', 'Dispatched Filled'), ('Received Filled', 'Received Filled')], max_length=30, null=True, verbose_name="QwikVendor's Remark"),
        ),
        migrations.CreateModel(
            name='Owing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cylinder', models.CharField(max_length=110, null=True, verbose_name='Cylinder Id')),
                ('category', models.CharField(max_length=12, null=True)),
                ('outlet', models.CharField(max_length=30, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created',),
                'index_together': {('id',)},
            },
        ),
        migrations.CreateModel(
            name='Cylinder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cylinder', models.CharField(max_length=30, null=True, verbose_name='Cylinder Id')),
                ('category', models.CharField(max_length=12, null=True)),
                ('outlet', models.CharField(max_length=30, null=True)),
                ('vendor_product_status', models.CharField(choices=[('Dispatched to Plant', 'Dispatched to Plant'), ('Returned Empty to QwikLet', 'Returned Empty to QwikLet'), ('Delivered Filled to QwikLet', 'Delivered Filled to QwikLet'), ('Released Filled to QwikPartner', 'Released Filled to QwikPartner'), ('Delivered to QwikCustomer', 'Delivered to QwikCustomer'), ('Returned Filled to QwikLet', 'Returned Filled to QwikLet'), ('Delivered to QwikCustomer', 'Delivered to QwikCustomer')], max_length=30, null=True, verbose_name="QwikVendor's Remark")),
                ('partner_product_status', models.CharField(blank=True, choices=[('Received Empty from QwikCustomer', 'Received Empty from QwikCustomer'), ('Returned Empty to QwikLet', 'Returned Empty to QwikLet'), ('Dispatched to Plant', 'Dispatched to Plant'), ('Delivered Filled to QwikLet', 'Delivered Filled to QwikLet'), ('Dispatched Filled to QwikCustomer', 'Dispatched Filled to QwikCustomer'), ('Delivered to QwikCustomer', 'Delivered to QwikCustomer'), ('Returned Filled to QwikLet', 'Returned Filled to QwikLet')], max_length=35, null=True, verbose_name="QwikPartner's Remark")),
                ('partner_confirm', models.BooleanField(blank=True, null=True, verbose_name="QwikPartner's Confirmation")),
                ('vendor_confirm', models.BooleanField(blank=True, default=False, null=True, verbose_name="QwikVendor's Confirmation")),
                ('who', models.CharField(blank=True, max_length=8, null=True)),
                ('who_2', models.CharField(blank=True, max_length=9, null=True)),
                ('who2', models.CharField(blank=True, max_length=8, null=True)),
                ('who2_2', models.CharField(blank=True, max_length=9, null=True)),
                ('who3', models.CharField(blank=True, max_length=8, null=True)),
                ('who3_2', models.CharField(blank=True, max_length=9, null=True)),
                ('who4', models.CharField(blank=True, max_length=8, null=True)),
                ('who4_2', models.CharField(blank=True, max_length=9, null=True)),
                ('who5', models.CharField(blank=True, max_length=8, null=True)),
                ('who5_2', models.CharField(blank=True, max_length=9, null=True)),
                ('who8', models.CharField(blank=True, max_length=19, null=True)),
                ('who8_1', models.CharField(blank=True, max_length=8, null=True)),
                ('who8_2', models.CharField(blank=True, max_length=9, null=True)),
                ('customer_product_status', models.CharField(blank=True, choices=[('Returned Empty to QwikPartner', 'Returned Empty to QwikPartner'), ('Received Filled', 'Received Filled')], max_length=35, null=True, verbose_name="QwikCustomer's Remark")),
                ('admin_product_status', models.CharField(blank=True, choices=[('Received Empty from QwikCustomer', 'Received Empty from QwikCustomer'), ('Returned Empty to QwikLet', 'Returned Empty to QwikLet'), ('Dispatched to Plant', 'Dispatched to Plant'), ('Delivered Filled to QwikLet', 'Delivered Filled to QwikLet'), ('Dispatched Filled to QwikCustomer', 'Dispatched Filled to QwikCustomer'), ('Delivered to QwikCustomer', 'Delivered to QwikCustomer'), ('Returned Filled to QwikLet', 'Returned Filled to QwikLet')], max_length=35, null=True, verbose_name="QwikAdmin's Remark")),
                ('admin_product', models.CharField(blank=True, max_length=20, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created',),
                'index_together': {('id',)},
            },
        ),
    ]
