# Generated by Django 3.2.4 on 2022-04-11 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20220331_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='mass',
            field=models.CharField(db_index=True, max_length=6, unique=True, verbose_name='LPG Weight'),
        ),
        migrations.AlterField(
            model_name='category',
            name='tare',
            field=models.CharField(db_index=True, max_length=6, null=True, unique=True, verbose_name='Tare Weight'),
        ),
        migrations.AlterField(
            model_name='category',
            name='test',
            field=models.CharField(db_index=True, max_length=6, null=True, verbose_name='Test Pressure'),
        ),
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Product Type'),
        ),
        migrations.AlterField(
            model_name='category',
            name='water',
            field=models.CharField(db_index=True, max_length=6, null=True, verbose_name='Water Capacity'),
        ),
        migrations.AlterField(
            model_name='category',
            name='working',
            field=models.CharField(db_index=True, max_length=6, null=True, verbose_name='Working Pressure'),
        ),
        migrations.AlterField(
            model_name='product',
            name='partner_product_status',
            field=models.CharField(blank=True, choices=[('Received Empty from QwikCustomer', 'Received Empty from QwikCustomer'), ('Returned Empty', 'Returned Empty'), ('Received Empty', 'Received Empty'), ('Received Filled', 'Received Filled'), ('Selected', 'Selected'), ('Unselected', 'Unselected')], max_length=35, null=True, verbose_name="QwikPartner's Remark"),
        ),
    ]
