# Generated by Django 3.2.7 on 2022-01-29 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20220129_1049'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cylinder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_product_status', models.CharField(choices=[('Dispatched Empty to Plant', 'Dispatched Empty to Plant'), ('Returned Empty to QwikLet', 'Returned Empty to QwikLet'), ('Delivered Filled to QwikLet', 'Delivered Filled to QwikLet'), ('Released Filled to QwikPartner', 'Released Filled to QwikPartner'), ('Delivered to QwikCustomer', 'Delivered to QwikCustomer'), ('Returned Filled to QwikLet', 'Returned Filled to QwikLet'), ('Delivered to QwikCustomer', 'Delivered to QwikCustomer'), ('Dispatched Empty', 'Dispatched Empty'), ('Received Empty', 'Received Empty'), ('Dispatched Filled', 'Dispatched Filled'), ('Received Filled', 'Received Filled')], max_length=30, null=True, verbose_name="QwikVendor's Remark")),
                ('vendor_product', models.CharField(blank=True, max_length=20, null=True)),
                ('vendor_consent', models.BooleanField(default=False, max_length=5)),
                ('partner_product_status', models.CharField(blank=True, choices=[('Returned Empty to QwikLet', 'Returned Empty to QwikLet'), ('Received Empty from QwikCustomer', 'Received Empty from QwikCustomer'), ('Delivered Filled to QwikLet', 'Delivered Filled to QwikLet'), ('Dispatched Filled to QwikCustomer', 'Dispatched Filled to QwikCustomer'), ('Delivered Filled to QwikCustomer', 'Delivered Filled to QwikCustomer'), ('Returned Filled to QwikLet', 'Returned Filled to QwikLet'), ('Dispatched Empty to Plant', 'Dispatched Empty to Plant'), ('Delivered Empty to Plant', 'Delivered Empty to Plant'), ('Returned Empty', 'Returned Empty'), ('Received Empty', 'Received Empty'), ('Received Filled', 'Received Filled')], max_length=35, null=True, verbose_name="QwikPartner's Remark")),
                ('partner_product', models.CharField(blank=True, max_length=20, null=True)),
                ('partner_consent', models.BooleanField(default=False, max_length=5)),
                ('customer_product_status', models.CharField(blank=True, choices=[('Returned Empty to QwikPartner', 'Returned Empty to QwikPartner'), ('Received Filled', 'Received Filled')], max_length=35, null=True, verbose_name="QwikCustomer's Remark")),
                ('customer_product', models.CharField(blank=True, max_length=20, null=True)),
                ('admin_product_status', models.CharField(blank=True, choices=[('Received Empty from QwikCustomer', 'Received Empty from QwikCustomer'), ('Returned Empty to QwikLet', 'Returned Empty to QwikLet'), ('Dispatched Empty to Plant', 'Dispatched Empty to Plant'), ('Delivered Filled to QwikLet', 'Delivered Filled to QwikLet'), ('Dispatched Filled to QwikCustomer', 'Dispatched Filled to QwikCustomer'), ('Delivered Filled to QwikCustomer', 'Delivered Filled to QwikCustomer'), ('Returned Filled to QwikLet', 'Returned Filled to QwikLet')], max_length=35, null=True, verbose_name="QwikAdmin's Remark")),
                ('admin_product', models.CharField(blank=True, max_length=20, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('cylinder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product', verbose_name='Cylinder Id')),
            ],
            options={
                'ordering': ('-created',),
                'index_together': {('id',)},
            },
        ),
    ]
