# Generated by Django 3.2.4 on 2022-04-11 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20220411_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='partner_product_status',
            field=models.CharField(blank=True, choices=[('Received Empty from QwikCustomer', 'Received Empty from QwikCustomer'), ('Returned Empty', 'Returned Empty'), ('Received Empty', 'Received Empty'), ('Received Filled', 'Received Filled'), ('Selected', 'Selected'), ('Unselected', 'Unselected')], default='Unselected', max_length=35, null=True, verbose_name="QwikPartner's Remark"),
        ),
    ]
