# Generated by Django 3.2.4 on 2022-04-17 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_partner_product_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='admin_product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='admin_product_status',
        ),
        migrations.RemoveField(
            model_name='product',
            name='customer_product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='customer_product_status',
        ),
    ]
