# Generated by Django 3.2.7 on 2022-01-29 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_cylinder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cylinder',
            name='partner_consent',
        ),
        migrations.RemoveField(
            model_name='cylinder',
            name='vendor_consent',
        ),
        migrations.AlterField(
            model_name='cylinder',
            name='partner_product_status',
            field=models.CharField(blank=True, choices=[('Returned Empty to QwikLet', 'Returned Empty to QwikLet'), ('Received Empty from QwikCustomer', 'Received Empty from QwikCustomer'), ('Delivered Filled to QwikLet', 'Delivered Filled to QwikLet'), ('Dispatched Filled to QwikCustomer', 'Dispatched Filled to QwikCustomer'), ('Delivered Filled to QwikCustomer', 'Delivered Filled to QwikCustomer'), ('Returned Filled to QwikLet', 'Returned Filled to QwikLet'), ('Dispatched Empty to Plant', 'Dispatched Empty to Plant'), ('Delivered Empty to Plant', 'Delivered Empty to Plant'), ('Agree', 'Agree'), ('Disagree', 'Disagree')], max_length=35, null=True, verbose_name="QwikPartner's Remark"),
        ),
        migrations.AlterField(
            model_name='cylinder',
            name='vendor_product_status',
            field=models.CharField(choices=[('Dispatched Empty to Plant', 'Dispatched Empty to Plant'), ('Returned Empty to QwikLet', 'Returned Empty to QwikLet'), ('Delivered Filled to QwikLet', 'Delivered Filled to QwikLet'), ('Released Filled to QwikPartner', 'Released Filled to QwikPartner'), ('Delivered to QwikCustomer', 'Delivered to QwikCustomer'), ('Returned Filled to QwikLet', 'Returned Filled to QwikLet'), ('Delivered to QwikCustomer', 'Delivered to QwikCustomer'), ('Agree', 'Agree'), ('Disagree', 'Disagree')], max_length=30, null=True, verbose_name="QwikVendor's Remark"),
        ),
    ]
