# Generated by Django 3.2.4 on 2022-05-04 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20220417_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='mass',
            field=models.CharField(max_length=6, unique=True, verbose_name='LPG Weight'),
        ),
        migrations.AlterField(
            model_name='category',
            name='tare',
            field=models.CharField(max_length=6, null=True, unique=True, verbose_name='Tare Weight'),
        ),
        migrations.AlterField(
            model_name='category',
            name='test',
            field=models.CharField(max_length=6, null=True, verbose_name='Test Pressure'),
        ),
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(max_length=20, unique=True, verbose_name='Product Type'),
        ),
        migrations.AlterField(
            model_name='category',
            name='water',
            field=models.CharField(max_length=6, null=True, verbose_name='Water Capacity'),
        ),
        migrations.AlterField(
            model_name='category',
            name='working',
            field=models.CharField(max_length=6, null=True, verbose_name='Working Pressure'),
        ),
    ]
