# Generated by Django 3.2.4 on 2022-01-30 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_cylinder_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cylinder',
            name='customer_product_status',
            field=models.CharField(blank=True, choices=[('Returned Empty to QwikPartner', 'Returned Empty to QwikPartner'), ('Received Filled', 'Received Filled'), ('Agree', 'Agree'), ('Disagree', 'Disagree')], max_length=35, null=True, verbose_name="QwikCustomer's Remark"),
        ),
    ]
