# Generated by Django 3.2.4 on 2022-05-04 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_category_price0'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='price0',
        ),
    ]
