# Generated by Django 3.2.4 on 2022-02-25 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_cylinder_customer_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cylinder',
            name='partner_product_confirm',
            field=models.CharField(blank=True, choices=[('Accept', 'Accept'), ('Decline', 'Decline')], max_length=35, null=True, verbose_name="QwikPartner's Confirmation"),
        ),
        migrations.AlterField(
            model_name='cylinder',
            name='admin_product_status',
            field=models.CharField(blank=True, choices=[('Received Empty from QwikCustomer', 'Received Empty from QwikCustomer'), ('Returned Empty to QwikLet', 'Returned Empty to QwikLet'), ('Dispatched to Plant', 'Dispatched to Plant'), ('Delivered Filled to QwikLet', 'Delivered Filled to QwikLet'), ('Dispatched Filled to QwikCustomer', 'Dispatched Filled to QwikCustomer'), ('Delivered to QwikCustomer', 'Delivered to QwikCustomer'), ('Returned Filled to QwikLet', 'Returned Filled to QwikLet')], max_length=35, null=True, verbose_name="QwikAdmin's Remark"),
        ),
        migrations.AlterField(
            model_name='cylinder',
            name='partner_product_status',
            field=models.CharField(blank=True, choices=[('Received Empty from QwikCustomer', 'Received Empty from QwikCustomer'), ('Returned Empty to QwikLet', 'Returned Empty to QwikLet'), ('Dispatched to Plant', 'Dispatched to Plant'), ('Delivered Filled to QwikLet', 'Delivered Filled to QwikLet'), ('Dispatched Filled to QwikCustomer', 'Dispatched Filled to QwikCustomer'), ('Delivered to QwikCustomer', 'Delivered to QwikCustomer'), ('Returned Filled to QwikLet', 'Returned Filled to QwikLet'), ('Accept', 'Agree'), ('Decline', 'Disagree')], max_length=35, null=True, verbose_name="QwikPartner's Remark"),
        ),
        migrations.AlterField(
            model_name='cylinder',
            name='vendor_product_status',
            field=models.CharField(choices=[('Dispatched to Plant', 'Dispatched to Plant'), ('Returned Empty to QwikLet', 'Returned Empty to QwikLet'), ('Delivered Filled to QwikLet', 'Delivered Filled to QwikLet'), ('Released Filled to QwikPartner', 'Released Filled to QwikPartner'), ('Delivered to QwikCustomer', 'Delivered to QwikCustomer'), ('Returned Filled to QwikLet', 'Returned Filled to QwikLet'), ('Delivered to QwikCustomer', 'Delivered to QwikCustomer'), ('Agree', 'Agree'), ('Disagree', 'Disagree')], max_length=30, null=True, verbose_name="QwikVendor's Remark"),
        ),
        migrations.AlterField(
            model_name='product',
            name='admin_product_status',
            field=models.CharField(blank=True, choices=[('Received Empty from QwikCustomer', 'Received Empty from QwikCustomer'), ('Returned Empty to QwikLet', 'Returned Empty to QwikLet'), ('Dispatched to Plant', 'Dispatched to Plant'), ('Delivered Filled to QwikLet', 'Delivered Filled to QwikLet'), ('Dispatched Filled to QwikCustomer', 'Dispatched Filled to QwikCustomer'), ('Delivered to QwikCustomer', 'Delivered to QwikCustomer'), ('Returned Filled to QwikLet', 'Returned Filled to QwikLet')], max_length=35, null=True, verbose_name="QwikAdmin's Remark"),
        ),
        migrations.AlterField(
            model_name='product',
            name='partner_product_status',
            field=models.CharField(blank=True, choices=[('Returned Empty to QwikLet', 'Returned Empty to QwikLet'), ('Received Empty from QwikCustomer', 'Received Empty from QwikCustomer'), ('Delivered Filled to QwikLet', 'Delivered Filled to QwikLet'), ('Dispatched Filled to QwikCustomer', 'Dispatched Filled to QwikCustomer'), ('Delivered to QwikCustomer', 'Delivered to QwikCustomer'), ('Returned Filled to QwikLet', 'Returned Filled to QwikLet'), ('Dispatched to Plant', 'Dispatched to Plant'), ('Delivered Empty to Plant', 'Delivered Empty to Plant'), ('Returned Empty', 'Returned Empty'), ('Received Empty', 'Received Empty'), ('Received Filled', 'Received Filled')], max_length=35, null=True, verbose_name="QwikPartner's Remark"),
        ),
        migrations.AlterField(
            model_name='product',
            name='vendor_product_status',
            field=models.CharField(choices=[('Dispatched to Plant', 'Dispatched to Plant'), ('Returned Empty to QwikLet', 'Returned Empty to QwikLet'), ('Delivered Filled to QwikLet', 'Delivered Filled to QwikLet'), ('Released Filled to QwikPartner', 'Released Filled to QwikPartner'), ('Delivered to QwikCustomer', 'Delivered to QwikCustomer'), ('Returned Filled to QwikLet', 'Returned Filled to QwikLet'), ('Delivered to QwikCustomer', 'Delivered to QwikCustomer'), ('Dispatched Empty', 'Dispatched Empty'), ('Received Empty', 'Received Empty'), ('Dispatched Filled', 'Dispatched Filled'), ('Received Filled', 'Received Filled')], max_length=30, null=True, verbose_name="QwikVendor's Remark"),
        ),
    ]
