# Generated by Django 3.2.4 on 2022-02-25 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20220225_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cylinder',
            name='cylinder',
            field=models.CharField(max_length=30, null=True, verbose_name='Cylinder Id'),
        ),
        migrations.AlterField(
            model_name='cylinder',
            name='partner_product_status',
            field=models.CharField(blank=True, choices=[('Received Empty from QwikCustomer', 'Received Empty from QwikCustomer'), ('Returned Empty to QwikLet', 'Returned Empty to QwikLet'), ('Dispatched to Plant', 'Dispatched to Plant'), ('Delivered Filled to QwikLet', 'Delivered Filled to QwikLet'), ('Dispatched Filled to QwikCustomer', 'Dispatched Filled to QwikCustomer'), ('Delivered to QwikCustomer', 'Delivered to QwikCustomer'), ('Returned Filled to QwikLet', 'Returned Filled to QwikLet')], max_length=35, null=True, verbose_name="QwikPartner's Remark"),
        ),
    ]
