# Generated by Django 3.2.4 on 2023-01-09 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_category_price0'),
    ]

    operations = [
        migrations.AddField(
            model_name='cylinder',
            name='partner_transfer_mode',
            field=models.CharField(blank=True, choices=[('Transfer', 'Transfer'), ('Receiving', 'Receiving')], max_length=9, null=True, verbose_name="Partner's Transfer Remark"),
        ),
        migrations.AddField(
            model_name='cylinder',
            name='transfer_product_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cylinder',
            name='vendor_transfer_mode',
            field=models.CharField(blank=True, choices=[('Transfer', 'Transfer'), ('Receiving', 'Receiving')], max_length=9, null=True, verbose_name="Vendor's Transfer Remark"),
        ),
    ]
