# Generated by Django 3.2.4 on 2022-02-25 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20220225_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='cylinder',
            name='category',
            field=models.CharField(max_length=12, null=True, verbose_name=''),
        ),
    ]
