# Generated by Django 3.2.4 on 2023-01-11 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20230109_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='cylinder',
            name='transferred',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
