# Generated by Django 3.2.4 on 2022-02-26 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_cylinder_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cylinder',
            name='customer_product',
        ),
        migrations.RemoveField(
            model_name='cylinder',
            name='partner_product',
        ),
        migrations.RemoveField(
            model_name='cylinder',
            name='partner_product_confirm',
        ),
        migrations.RemoveField(
            model_name='cylinder',
            name='vendor_product',
        ),
        migrations.AddField(
            model_name='cylinder',
            name='partner_confirm',
            field=models.CharField(blank=True, choices=[('Accept', 'Accept'), ('Decline', 'Decline')], max_length=35, null=True, verbose_name="QwikVendor's Confirmation"),
        ),
        migrations.AlterField(
            model_name='cylinder',
            name='customer_product_status',
            field=models.CharField(blank=True, choices=[('Returned Empty to QwikPartner', 'Returned Empty to QwikPartner'), ('Received Filled', 'Received Filled')], max_length=35, null=True, verbose_name="QwikCustomer's Remark"),
        ),
    ]
