# Generated by Django 3.2.4 on 2022-02-26 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20220226_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='cylinder',
            name='vendor_confirm',
            field=models.CharField(blank=True, choices=[('Accept', 'Accept'), ('Decline', 'Decline')], max_length=35, null=True, verbose_name="QwikVendor's Confirmation"),
        ),
        migrations.AlterField(
            model_name='cylinder',
            name='partner_confirm',
            field=models.CharField(blank=True, choices=[('Accept', 'Accept'), ('Decline', 'Decline')], max_length=35, null=True, verbose_name="QwikPartner's Confirmation"),
        ),
    ]
