# Generated by Django 3.2.4 on 2022-02-26 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_cylinder_partner_confirm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cylinder',
            name='vendor_confirm',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name="QwikVendor's Confirmation"),
        ),
    ]
