# Generated by Django 3.2.4 on 2022-02-26 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_cylinder_vendor_confirm'),
    ]

    operations = [
        migrations.AddField(
            model_name='cylinder',
            name='who',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name=''),
        ),
    ]
