# Generated by Django 3.2.4 on 2022-02-26 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_cylinder_who'),
    ]

    operations = [
        migrations.AddField(
            model_name='cylinder',
            name='who2',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='cylinder',
            name='category',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='cylinder',
            name='who',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
