# Generated by Django 3.2.4 on 2022-02-26 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_auto_20220226_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='cylinder',
            name='outlet',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
