# Generated by Django 3.2.4 on 2022-02-27 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_cylinder_outlet'),
    ]

    operations = [
        migrations.AddField(
            model_name='cylinder',
            name='who3',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
