# Generated by Django 3.2.4 on 2022-02-27 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_cylinder_who3'),
    ]

    operations = [
        migrations.AddField(
            model_name='cylinder',
            name='who4',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
