# Generated by Django 3.2.4 on 2022-02-27 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_cylinder_who4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cylinder',
            name='partner_confirm',
            field=models.BooleanField(blank=True, null=True, verbose_name="QwikPartner's Confirmation"),
        ),
    ]
