# Generated by Django 3.2.4 on 2022-02-28 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_alter_cylinder_partner_confirm'),
    ]

    operations = [
        migrations.AddField(
            model_name='cylinder',
            name='who_2',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
