# Generated by Django 3.2.4 on 2022-02-28 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_cylinder_who_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='cylinder',
            name='who2_2',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='cylinder',
            name='who',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='cylinder',
            name='who2',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='cylinder',
            name='who_2',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
