# Generated by Django 3.2.4 on 2022-02-28 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_auto_20220228_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='cylinder',
            name='who3_2',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
