# Generated by Django 3.2.4 on 2022-02-28 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_cylinder_who3_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cylinder',
            name='who3',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
