# Generated by Django 3.2.4 on 2022-02-28 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_alter_cylinder_who3'),
    ]

    operations = [
        migrations.AddField(
            model_name='cylinder',
            name='who4_2',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='cylinder',
            name='who4',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
