# Generated by Django 3.2.4 on 2022-03-01 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_auto_20220228_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='cylinder',
            name='who5',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='cylinder',
            name='who5_2',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
