# Generated by Django 3.2.4 on 2022-03-02 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_auto_20220301_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='cylinder',
            name='who8',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='cylinder',
            name='who8_2',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
