# Generated by Django 3.2.4 on 2022-03-02 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_auto_20220302_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='cylinder',
            name='who8_1',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
