# Generated by Django 3.2.4 on 2022-03-02 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_cylinder_who8_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cylinder',
            name='who8',
            field=models.CharField(blank=True, max_length=19, null=True),
        ),
    ]
