# Generated by Django 3.2.4 on 2022-03-07 05:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0030_alter_cylinder_who8'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cylinder', models.CharField(max_length=30, null=True, verbose_name='Cylinder Id')),
                ('category', models.CharField(max_length=12, null=True)),
                ('outlet', models.CharField(max_length=30, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created',),
                'index_together': {('id',)},
            },
        ),
    ]
