# Generated by Django 3.2.4 on 2022-03-13 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_owing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='partner_product_status',
            field=models.CharField(blank=True, choices=[('Received Empty from QwikCustomer', 'Received Empty from QwikCustomer'), ('Returned Empty', 'Returned Empty'), ('Received Empty', 'Received Empty'), ('Received Filled', 'Received Filled')], max_length=35, null=True, verbose_name="QwikPartner's Remark"),
        ),
        migrations.AlterField(
            model_name='product',
            name='vendor_product_status',
            field=models.CharField(choices=[('Dispatched to Plant', 'Dispatched to Plant'), ('Released Filled to QwikPartner', 'Released Filled to QwikPartner'), ('Dispatched Empty', 'Dispatched Empty'), ('Received Empty', 'Received Empty'), ('Dispatched Filled', 'Dispatched Filled'), ('Received Filled', 'Received Filled')], max_length=30, null=True, verbose_name="QwikVendor's Remark"),
        ),
    ]
