# Generated by Django 3.2.4 on 2022-03-14 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0032_auto_20220313_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owing',
            name='cylinder',
            field=models.CharField(max_length=110, null=True, verbose_name='Cylinder Id'),
        ),
    ]
